# Generated by Django 5.1.1 on 2024-10-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('trailer_url', models.URLField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('development_history', models.TextField(blank=True, null=True)),
                ('community_involvement', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='game_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.game')),
            ],
        ),
    ]
